use crate::tofu::types::{BackendCatalogEntry, ProviderFieldSchema, ProviderFieldType, FieldOption};

/// Return the static backend type catalog.
pub fn get_backend_catalog() -> Vec<BackendCatalogEntry> {
    vec![
        BackendCatalogEntry {
            id: "s3".into(),
            name: "S3".into(),
            description: "Store state in an S3-compatible bucket".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "bucket".into(),
                    label: "Bucket".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("S3 bucket name for state storage".into()),
                },
                ProviderFieldSchema {
                    name: "key".into(),
                    label: "Key".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("terraform.tfstate".into()),
                    options: vec![],
                    help_text: Some("Path to the state file within the bucket".into()),
                },
                ProviderFieldSchema {
                    name: "region".into(),
                    label: "Region".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("us-east-1".into()),
                    options: vec![],
                    help_text: Some("AWS region of the S3 bucket".into()),
                },
                ProviderFieldSchema {
                    name: "encrypt".into(),
                    label: "Encrypt".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Enable server-side encryption of the state file".into()),
                },
                ProviderFieldSchema {
                    name: "dynamodb_table".into(),
                    label: "DynamoDB Table".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("DynamoDB table for state locking".into()),
                },
            ],
        },
        BackendCatalogEntry {
            id: "azurerm".into(),
            name: "Azure RM".into(),
            description: "Store state in Azure Blob Storage".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "resource_group_name".into(),
                    label: "Resource Group".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure resource group name".into()),
                },
                ProviderFieldSchema {
                    name: "storage_account_name".into(),
                    label: "Storage Account".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure storage account name".into()),
                },
                ProviderFieldSchema {
                    name: "container_name".into(),
                    label: "Container".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("tfstate".into()),
                    options: vec![],
                    help_text: Some("Blob container name".into()),
                },
                ProviderFieldSchema {
                    name: "key".into(),
                    label: "Key".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("terraform.tfstate".into()),
                    options: vec![],
                    help_text: Some("Blob name for the state file".into()),
                },
            ],
        },
        BackendCatalogEntry {
            id: "gcs".into(),
            name: "Google Cloud Storage".into(),
            description: "Store state in a GCS bucket".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "bucket".into(),
                    label: "Bucket".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("GCS bucket name".into()),
                },
                ProviderFieldSchema {
                    name: "prefix".into(),
                    label: "Prefix".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("terraform/state".into()),
                    options: vec![],
                    help_text: Some("Path prefix within the bucket".into()),
                },
            ],
        },
        BackendCatalogEntry {
            id: "local".into(),
            name: "Local".into(),
            description: "Store state on the local filesystem".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "path".into(),
                    label: "Path".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("terraform.tfstate".into()),
                    options: vec![],
                    help_text: Some("Path to the local state file".into()),
                },
            ],
        },
        BackendCatalogEntry {
            id: "consul".into(),
            name: "Consul".into(),
            description: "Store state in HashiCorp Consul".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "address".into(),
                    label: "Address".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("127.0.0.1:8500".into()),
                    options: vec![],
                    help_text: Some("Consul HTTP API address".into()),
                },
                ProviderFieldSchema {
                    name: "path".into(),
                    label: "Path".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("terraform/state".into()),
                    options: vec![],
                    help_text: Some("KV path for the state".into()),
                },
                ProviderFieldSchema {
                    name: "scheme".into(),
                    label: "Scheme".into(),
                    field_type: ProviderFieldType::Select,
                    required: false,
                    default_value: Some("http".into()),
                    options: vec![
                        FieldOption { label: "HTTP".into(), value: "http".into() },
                        FieldOption { label: "HTTPS".into(), value: "https".into() },
                    ],
                    help_text: Some("URL scheme (http or https)".into()),
                },
            ],
        },
        BackendCatalogEntry {
            id: "pg".into(),
            name: "PostgreSQL".into(),
            description: "Store state in a PostgreSQL database".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "conn_str".into(),
                    label: "Connection String".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("PostgreSQL connection string (e.g. postgres://user:pass@host/db)".into()),
                },
                ProviderFieldSchema {
                    name: "schema_name".into(),
                    label: "Schema".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("terraform_remote_state".into()),
                    options: vec![],
                    help_text: Some("PostgreSQL schema name".into()),
                },
            ],
        },
        BackendCatalogEntry {
            id: "http".into(),
            name: "HTTP".into(),
            description: "Store state via an HTTP REST endpoint".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "address".into(),
                    label: "Address".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("URL to GET/POST the state".into()),
                },
                ProviderFieldSchema {
                    name: "lock_address".into(),
                    label: "Lock Address".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("URL for state locking (LOCK/UNLOCK)".into()),
                },
                ProviderFieldSchema {
                    name: "unlock_address".into(),
                    label: "Unlock Address".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("URL for state unlocking".into()),
                },
            ],
        },
    ]
}
