use crate::tofu::types::{FieldOption, ProviderCatalogEntry, ProviderFieldSchema, ProviderFieldType};

/// Return the static curated provider catalog.
pub fn get_provider_catalog() -> Vec<ProviderCatalogEntry> {
    vec![
        ProviderCatalogEntry {
            id: "aws".into(),
            name: "AWS".into(),
            source: "hashicorp/aws".into(),
            description: "Amazon Web Services provider for managing AWS resources".into(),
            category: "Cloud".into(),
            icon: "aws".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "region".into(),
                    label: "Region".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("us-east-1".into()),
                    options: vec![
                        FieldOption { label: "US East (N. Virginia)".into(), value: "us-east-1".into() },
                        FieldOption { label: "US East (Ohio)".into(), value: "us-east-2".into() },
                        FieldOption { label: "US West (N. California)".into(), value: "us-west-1".into() },
                        FieldOption { label: "US West (Oregon)".into(), value: "us-west-2".into() },
                        FieldOption { label: "EU (Ireland)".into(), value: "eu-west-1".into() },
                        FieldOption { label: "EU (Frankfurt)".into(), value: "eu-central-1".into() },
                        FieldOption { label: "EU (London)".into(), value: "eu-west-2".into() },
                        FieldOption { label: "EU (Paris)".into(), value: "eu-west-3".into() },
                        FieldOption { label: "EU (Stockholm)".into(), value: "eu-north-1".into() },
                        FieldOption { label: "Asia Pacific (Tokyo)".into(), value: "ap-northeast-1".into() },
                        FieldOption { label: "Asia Pacific (Seoul)".into(), value: "ap-northeast-2".into() },
                        FieldOption { label: "Asia Pacific (Singapore)".into(), value: "ap-southeast-1".into() },
                        FieldOption { label: "Asia Pacific (Sydney)".into(), value: "ap-southeast-2".into() },
                        FieldOption { label: "Asia Pacific (Mumbai)".into(), value: "ap-south-1".into() },
                        FieldOption { label: "Canada (Central)".into(), value: "ca-central-1".into() },
                        FieldOption { label: "South America (Sao Paulo)".into(), value: "sa-east-1".into() },
                    ],
                    help_text: Some("AWS region for resource deployment".into()),
                },
                ProviderFieldSchema {
                    name: "access_key".into(),
                    label: "Access Key".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("AWS access key ID (leave empty to use env or profile)".into()),
                },
                ProviderFieldSchema {
                    name: "secret_key".into(),
                    label: "Secret Key".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("AWS secret access key".into()),
                },
                ProviderFieldSchema {
                    name: "profile".into(),
                    label: "Profile".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("AWS CLI profile name".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "azurerm".into(),
            name: "Azure".into(),
            source: "hashicorp/azurerm".into(),
            description: "Azure Resource Manager provider for Microsoft Azure".into(),
            category: "Cloud".into(),
            icon: "azure".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "subscription_id".into(),
                    label: "Subscription ID".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure subscription ID".into()),
                },
                ProviderFieldSchema {
                    name: "tenant_id".into(),
                    label: "Tenant ID".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure Active Directory tenant ID".into()),
                },
                ProviderFieldSchema {
                    name: "client_id".into(),
                    label: "Client ID".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Service principal client ID".into()),
                },
                ProviderFieldSchema {
                    name: "client_secret".into(),
                    label: "Client Secret".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Service principal client secret".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "google".into(),
            name: "Google Cloud".into(),
            source: "hashicorp/google".into(),
            description: "Google Cloud Platform provider for managing GCP resources".into(),
            category: "Cloud".into(),
            icon: "gcp".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "project".into(),
                    label: "Project".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("GCP project ID".into()),
                },
                ProviderFieldSchema {
                    name: "region".into(),
                    label: "Region".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("us-central1".into()),
                    options: vec![
                        FieldOption { label: "US Central (Iowa)".into(), value: "us-central1".into() },
                        FieldOption { label: "US East (S. Carolina)".into(), value: "us-east1".into() },
                        FieldOption { label: "US West (Oregon)".into(), value: "us-west1".into() },
                        FieldOption { label: "Europe West (Belgium)".into(), value: "europe-west1".into() },
                        FieldOption { label: "Europe West (London)".into(), value: "europe-west2".into() },
                        FieldOption { label: "Europe West (Frankfurt)".into(), value: "europe-west3".into() },
                        FieldOption { label: "Asia East (Taiwan)".into(), value: "asia-east1".into() },
                        FieldOption { label: "Asia Northeast (Tokyo)".into(), value: "asia-northeast1".into() },
                        FieldOption { label: "Asia Southeast (Singapore)".into(), value: "asia-southeast1".into() },
                        FieldOption { label: "Australia Southeast (Sydney)".into(), value: "australia-southeast1".into() },
                    ],
                    help_text: Some("Default GCP region for resources".into()),
                },
                ProviderFieldSchema {
                    name: "credentials".into(),
                    label: "Credentials JSON".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Service account JSON key (leave empty to use ADC)".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "digitalocean".into(),
            name: "DigitalOcean".into(),
            source: "digitalocean/digitalocean".into(),
            description: "DigitalOcean provider for managing DO resources".into(),
            category: "Cloud".into(),
            icon: "digitalocean".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "token".into(),
                    label: "API Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("DigitalOcean personal access token".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "cloudflare".into(),
            name: "Cloudflare".into(),
            source: "cloudflare/cloudflare".into(),
            description: "Cloudflare provider for DNS, CDN, and security".into(),
            category: "CDN & DNS".into(),
            icon: "cloudflare".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "api_token".into(),
                    label: "API Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Cloudflare API token with appropriate permissions".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "kubernetes".into(),
            name: "Kubernetes".into(),
            source: "hashicorp/kubernetes".into(),
            description: "Kubernetes provider for managing K8s resources".into(),
            category: "Container".into(),
            icon: "kubernetes".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "config_path".into(),
                    label: "Kubeconfig Path".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("~/.kube/config".into()),
                    options: vec![],
                    help_text: Some("Path to kubeconfig file".into()),
                },
                ProviderFieldSchema {
                    name: "host".into(),
                    label: "Cluster Host".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Kubernetes API server URL".into()),
                },
                ProviderFieldSchema {
                    name: "token".into(),
                    label: "Bearer Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Service account token for authentication".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "docker".into(),
            name: "Docker".into(),
            source: "kreuzwerker/docker".into(),
            description: "Docker provider for managing containers and images".into(),
            category: "Container".into(),
            icon: "docker".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "host".into(),
                    label: "Docker Host".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("unix:///var/run/docker.sock".into()),
                    options: vec![],
                    help_text: Some("Docker daemon socket or TCP address".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "helm".into(),
            name: "Helm".into(),
            source: "hashicorp/helm".into(),
            description: "Helm provider for managing Kubernetes charts".into(),
            category: "Container".into(),
            icon: "helm".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "config_path".into(),
                    label: "Kubeconfig Path".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("~/.kube/config".into()),
                    options: vec![],
                    help_text: Some("Path to kubeconfig file for Helm releases".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "github".into(),
            name: "GitHub".into(),
            source: "integrations/github".into(),
            description: "GitHub provider for managing repos, teams, and org settings".into(),
            category: "VCS".into(),
            icon: "github".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "token".into(),
                    label: "Personal Access Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("GitHub PAT with repo/org permissions".into()),
                },
                ProviderFieldSchema {
                    name: "owner".into(),
                    label: "Owner".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("GitHub organization or user".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "gitlab".into(),
            name: "GitLab".into(),
            source: "gitlabhq/gitlab".into(),
            description: "GitLab provider for managing projects and groups".into(),
            category: "VCS".into(),
            icon: "gitlab".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "token".into(),
                    label: "Access Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("GitLab personal or group access token".into()),
                },
                ProviderFieldSchema {
                    name: "base_url".into(),
                    label: "Base URL".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("https://gitlab.com/api/v4".into()),
                    options: vec![],
                    help_text: Some("GitLab API URL (for self-hosted instances)".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "hcloud".into(),
            name: "Hetzner Cloud".into(),
            source: "hetznercloud/hcloud".into(),
            description: "Hetzner Cloud provider for managing servers and networks".into(),
            category: "Cloud".into(),
            icon: "hetzner".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "token".into(),
                    label: "API Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Hetzner Cloud API token".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "linode".into(),
            name: "Linode".into(),
            source: "linode/linode".into(),
            description: "Linode provider for managing Akamai cloud resources".into(),
            category: "Cloud".into(),
            icon: "linode".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "token".into(),
                    label: "API Token".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Linode personal access token".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "ovh".into(),
            name: "OVH".into(),
            source: "ovh/ovh".into(),
            description: "OVH provider for managing OVHcloud services".into(),
            category: "Cloud".into(),
            icon: "ovh".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "endpoint".into(),
                    label: "Endpoint".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("ovh-eu".into()),
                    options: vec![
                        FieldOption { label: "OVH Europe".into(), value: "ovh-eu".into() },
                        FieldOption { label: "OVH US".into(), value: "ovh-us".into() },
                        FieldOption { label: "OVH Canada".into(), value: "ovh-ca".into() },
                    ],
                    help_text: Some("OVH API endpoint region".into()),
                },
                ProviderFieldSchema {
                    name: "application_key".into(),
                    label: "Application Key".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("OVH application key".into()),
                },
                ProviderFieldSchema {
                    name: "application_secret".into(),
                    label: "Application Secret".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("OVH application secret".into()),
                },
            ],
        },
        ProviderCatalogEntry {
            id: "null".into(),
            name: "Null".into(),
            source: "hashicorp/null".into(),
            description: "Null provider for testing and placeholder resources".into(),
            category: "Utility".into(),
            icon: "utility".into(),
            fields: vec![],
        },
        ProviderCatalogEntry {
            id: "random".into(),
            name: "Random".into(),
            source: "hashicorp/random".into(),
            description: "Random provider for generating random values".into(),
            category: "Utility".into(),
            icon: "utility".into(),
            fields: vec![],
        },
    ]
}
