use crate::tofu::types::{DataSourceCatalogEntry, FieldOption, ProviderFieldSchema, ProviderFieldType};

/// Return the static curated data source catalog.
pub fn get_data_source_catalog() -> Vec<DataSourceCatalogEntry> {
    vec![
        DataSourceCatalogEntry {
            id: "aws_ami".into(),
            name: "AWS AMI".into(),
            data_type: "aws_ami".into(),
            provider_id: "aws".into(),
            category: "Compute".into(),
            description: "Look up an Amazon Machine Image (AMI)".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "most_recent".into(),
                    label: "Most Recent".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Return the most recent AMI if multiple match".into()),
                },
                ProviderFieldSchema {
                    name: "owners".into(),
                    label: "Owners".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Comma-separated list of AMI owners (e.g. amazon, self)".into()),
                },
                ProviderFieldSchema {
                    name: "name_regex".into(),
                    label: "Name Regex".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Regex to match the AMI name".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "aws_vpc".into(),
            name: "AWS VPC".into(),
            data_type: "aws_vpc".into(),
            provider_id: "aws".into(),
            category: "Network".into(),
            description: "Look up a VPC by ID or tags".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "id".into(),
                    label: "VPC ID".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Specific VPC ID to look up".into()),
                },
                ProviderFieldSchema {
                    name: "default".into(),
                    label: "Default VPC".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Whether to look up the default VPC".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "aws_subnet".into(),
            name: "AWS Subnet".into(),
            data_type: "aws_subnet".into(),
            provider_id: "aws".into(),
            category: "Network".into(),
            description: "Look up a subnet".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "id".into(),
                    label: "Subnet ID".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Specific subnet ID".into()),
                },
                ProviderFieldSchema {
                    name: "vpc_id".into(),
                    label: "VPC ID".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Filter by VPC ID".into()),
                },
                ProviderFieldSchema {
                    name: "availability_zone".into(),
                    label: "Availability Zone".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Filter by availability zone".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "aws_availability_zones".into(),
            name: "AWS Availability Zones".into(),
            data_type: "aws_availability_zones".into(),
            provider_id: "aws".into(),
            category: "Compute".into(),
            description: "List available availability zones in the current region".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "state".into(),
                    label: "State".into(),
                    field_type: ProviderFieldType::Select,
                    required: false,
                    default_value: Some("available".into()),
                    options: vec![
                        FieldOption { label: "Available".into(), value: "available".into() },
                        FieldOption { label: "Information".into(), value: "information".into() },
                    ],
                    help_text: Some("Filter zones by state".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "aws_caller_identity".into(),
            name: "AWS Caller Identity".into(),
            data_type: "aws_caller_identity".into(),
            provider_id: "aws".into(),
            category: "Utility".into(),
            description: "Get the current AWS account ID, user ID, and ARN".into(),
            fields: vec![],
        },
        DataSourceCatalogEntry {
            id: "aws_region".into(),
            name: "AWS Region".into(),
            data_type: "aws_region".into(),
            provider_id: "aws".into(),
            category: "Utility".into(),
            description: "Get information about the current AWS region".into(),
            fields: vec![],
        },
        DataSourceCatalogEntry {
            id: "azurerm_resource_group".into(),
            name: "Azure Resource Group".into(),
            data_type: "azurerm_resource_group".into(),
            provider_id: "azurerm".into(),
            category: "Compute".into(),
            description: "Look up an existing Azure resource group".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the resource group".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "azurerm_virtual_network".into(),
            name: "Azure Virtual Network".into(),
            data_type: "azurerm_virtual_network".into(),
            provider_id: "azurerm".into(),
            category: "Network".into(),
            description: "Look up an existing Azure virtual network".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the virtual network".into()),
                },
                ProviderFieldSchema {
                    name: "resource_group_name".into(),
                    label: "Resource Group".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the resource group".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "google_compute_image".into(),
            name: "Google Compute Image".into(),
            data_type: "google_compute_image".into(),
            provider_id: "google".into(),
            category: "Compute".into(),
            description: "Look up a Google Compute Engine image".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "family".into(),
                    label: "Image Family".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Image family name (e.g. debian-11)".into()),
                },
                ProviderFieldSchema {
                    name: "project".into(),
                    label: "Project".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Project that hosts the image (e.g. debian-cloud)".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "google_compute_network".into(),
            name: "Google Compute Network".into(),
            data_type: "google_compute_network".into(),
            provider_id: "google".into(),
            category: "Network".into(),
            description: "Look up a Google Compute Engine VPC network".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the VPC network".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "docker_image".into(),
            name: "Docker Image".into(),
            data_type: "docker_image".into(),
            provider_id: "docker".into(),
            category: "Container".into(),
            description: "Look up a Docker image by name".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Image Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Docker image name with optional tag (e.g. nginx:latest)".into()),
                },
            ],
        },
        DataSourceCatalogEntry {
            id: "local_file".into(),
            name: "Local File".into(),
            data_type: "local_file".into(),
            provider_id: "local".into(),
            category: "Utility".into(),
            description: "Read a local file".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "filename".into(),
                    label: "Filename".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Path to the file to read".into()),
                },
            ],
        },
    ]
}
