use crate::tofu::types::{FieldOption, ProviderFieldSchema, ProviderFieldType, ResourceCatalogEntry};

/// Return the static curated resource catalog.
pub fn get_resource_catalog() -> Vec<ResourceCatalogEntry> {
    vec![
        // ── AWS ──────────────────────────────────────────────
        ResourceCatalogEntry {
            id: "aws_instance".into(),
            name: "EC2 Instance".into(),
            resource_type: "aws_instance".into(),
            provider_id: "aws".into(),
            category: "Compute".into(),
            description: "An Amazon EC2 virtual server instance".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "ami".into(),
                    label: "AMI ID".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Amazon Machine Image ID (e.g. ami-0abcdef1234567890)".into()),
                },
                ProviderFieldSchema {
                    name: "instance_type".into(),
                    label: "Instance Type".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("t3.micro".into()),
                    options: vec![
                        FieldOption { label: "t3.micro".into(), value: "t3.micro".into() },
                        FieldOption { label: "t3.small".into(), value: "t3.small".into() },
                        FieldOption { label: "t3.medium".into(), value: "t3.medium".into() },
                        FieldOption { label: "t3.large".into(), value: "t3.large".into() },
                        FieldOption { label: "t3.xlarge".into(), value: "t3.xlarge".into() },
                        FieldOption { label: "m5.large".into(), value: "m5.large".into() },
                        FieldOption { label: "m5.xlarge".into(), value: "m5.xlarge".into() },
                        FieldOption { label: "c5.large".into(), value: "c5.large".into() },
                        FieldOption { label: "r5.large".into(), value: "r5.large".into() },
                    ],
                    help_text: Some("EC2 instance type".into()),
                },
                ProviderFieldSchema {
                    name: "key_name".into(),
                    label: "Key Pair Name".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the SSH key pair for access".into()),
                },
                ProviderFieldSchema {
                    name: "subnet_id".into(),
                    label: "Subnet ID".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("VPC subnet to launch into".into()),
                },
                ProviderFieldSchema {
                    name: "tags_name".into(),
                    label: "Name Tag".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Value for the Name tag".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "aws_s3_bucket".into(),
            name: "S3 Bucket".into(),
            resource_type: "aws_s3_bucket".into(),
            provider_id: "aws".into(),
            category: "Storage".into(),
            description: "An Amazon S3 storage bucket".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "bucket".into(),
                    label: "Bucket Name".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Globally unique bucket name (leave empty for auto-generated)".into()),
                },
                ProviderFieldSchema {
                    name: "force_destroy".into(),
                    label: "Force Destroy".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("false".into()),
                    options: vec![],
                    help_text: Some("Allow deletion even if bucket contains objects".into()),
                },
                ProviderFieldSchema {
                    name: "tags_name".into(),
                    label: "Name Tag".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Value for the Name tag".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "aws_security_group".into(),
            name: "Security Group".into(),
            resource_type: "aws_security_group".into(),
            provider_id: "aws".into(),
            category: "Network".into(),
            description: "An AWS VPC security group for firewall rules".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Group Name".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the security group".into()),
                },
                ProviderFieldSchema {
                    name: "description".into(),
                    label: "Description".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("Managed by OpenTofu".into()),
                    options: vec![],
                    help_text: Some("Description of the security group".into()),
                },
                ProviderFieldSchema {
                    name: "vpc_id".into(),
                    label: "VPC ID".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("VPC to create the security group in".into()),
                },
                ProviderFieldSchema {
                    name: "ingress_from_port".into(),
                    label: "Ingress From Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Start port for inbound rule".into()),
                },
                ProviderFieldSchema {
                    name: "ingress_to_port".into(),
                    label: "Ingress To Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("End port for inbound rule".into()),
                },
                ProviderFieldSchema {
                    name: "ingress_protocol".into(),
                    label: "Ingress Protocol".into(),
                    field_type: ProviderFieldType::Select,
                    required: false,
                    default_value: Some("tcp".into()),
                    options: vec![
                        FieldOption { label: "TCP".into(), value: "tcp".into() },
                        FieldOption { label: "UDP".into(), value: "udp".into() },
                        FieldOption { label: "All".into(), value: "-1".into() },
                    ],
                    help_text: Some("Protocol for inbound rule".into()),
                },
                ProviderFieldSchema {
                    name: "ingress_cidr_blocks".into(),
                    label: "Ingress CIDR Blocks".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("0.0.0.0/0".into()),
                    options: vec![],
                    help_text: Some("Comma-separated CIDR blocks for inbound rule".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "aws_db_instance".into(),
            name: "RDS Database".into(),
            resource_type: "aws_db_instance".into(),
            provider_id: "aws".into(),
            category: "Database".into(),
            description: "An Amazon RDS managed database instance".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "allocated_storage".into(),
                    label: "Storage (GB)".into(),
                    field_type: ProviderFieldType::Number,
                    required: true,
                    default_value: Some("20".into()),
                    options: vec![],
                    help_text: Some("Allocated storage in gigabytes".into()),
                },
                ProviderFieldSchema {
                    name: "engine".into(),
                    label: "Engine".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("postgres".into()),
                    options: vec![
                        FieldOption { label: "PostgreSQL".into(), value: "postgres".into() },
                        FieldOption { label: "MySQL".into(), value: "mysql".into() },
                        FieldOption { label: "MariaDB".into(), value: "mariadb".into() },
                    ],
                    help_text: Some("Database engine".into()),
                },
                ProviderFieldSchema {
                    name: "engine_version".into(),
                    label: "Engine Version".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Database engine version (e.g. 15.4)".into()),
                },
                ProviderFieldSchema {
                    name: "instance_class".into(),
                    label: "Instance Class".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("db.t3.micro".into()),
                    options: vec![
                        FieldOption { label: "db.t3.micro".into(), value: "db.t3.micro".into() },
                        FieldOption { label: "db.t3.small".into(), value: "db.t3.small".into() },
                        FieldOption { label: "db.t3.medium".into(), value: "db.t3.medium".into() },
                        FieldOption { label: "db.r5.large".into(), value: "db.r5.large".into() },
                    ],
                    help_text: Some("RDS instance class".into()),
                },
                ProviderFieldSchema {
                    name: "username".into(),
                    label: "Master Username".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("admin".into()),
                    options: vec![],
                    help_text: Some("Master database username".into()),
                },
                ProviderFieldSchema {
                    name: "password".into(),
                    label: "Master Password".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Master database password".into()),
                },
                ProviderFieldSchema {
                    name: "skip_final_snapshot".into(),
                    label: "Skip Final Snapshot".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Skip final snapshot on deletion".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "aws_vpc".into(),
            name: "VPC".into(),
            resource_type: "aws_vpc".into(),
            provider_id: "aws".into(),
            category: "Network".into(),
            description: "An Amazon VPC (Virtual Private Cloud)".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "cidr_block".into(),
                    label: "CIDR Block".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("10.0.0.0/16".into()),
                    options: vec![],
                    help_text: Some("The IPv4 CIDR block for the VPC".into()),
                },
                ProviderFieldSchema {
                    name: "enable_dns_support".into(),
                    label: "Enable DNS Support".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Enable DNS resolution in the VPC".into()),
                },
                ProviderFieldSchema {
                    name: "enable_dns_hostnames".into(),
                    label: "Enable DNS Hostnames".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("false".into()),
                    options: vec![],
                    help_text: Some("Enable DNS hostnames in the VPC".into()),
                },
                ProviderFieldSchema {
                    name: "tags_name".into(),
                    label: "Name Tag".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Value for the Name tag".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "aws_subnet".into(),
            name: "Subnet".into(),
            resource_type: "aws_subnet".into(),
            provider_id: "aws".into(),
            category: "Network".into(),
            description: "A subnet within an AWS VPC".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "vpc_id".into(),
                    label: "VPC ID".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("VPC ID to create the subnet in".into()),
                },
                ProviderFieldSchema {
                    name: "cidr_block".into(),
                    label: "CIDR Block".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("10.0.1.0/24".into()),
                    options: vec![],
                    help_text: Some("The IPv4 CIDR block for the subnet".into()),
                },
                ProviderFieldSchema {
                    name: "availability_zone".into(),
                    label: "Availability Zone".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("AZ to create the subnet in (e.g. us-east-1a)".into()),
                },
                ProviderFieldSchema {
                    name: "tags_name".into(),
                    label: "Name Tag".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Value for the Name tag".into()),
                },
            ],
        },

        // ── Azure ────────────────────────────────────────────
        ResourceCatalogEntry {
            id: "azurerm_resource_group".into(),
            name: "Resource Group".into(),
            resource_type: "azurerm_resource_group".into(),
            provider_id: "azurerm".into(),
            category: "Utility".into(),
            description: "An Azure resource group for organizing resources".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the resource group".into()),
                },
                ProviderFieldSchema {
                    name: "location".into(),
                    label: "Location".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("eastus".into()),
                    options: vec![
                        FieldOption { label: "East US".into(), value: "eastus".into() },
                        FieldOption { label: "West US".into(), value: "westus".into() },
                        FieldOption { label: "West Europe".into(), value: "westeurope".into() },
                        FieldOption { label: "North Europe".into(), value: "northeurope".into() },
                        FieldOption { label: "Southeast Asia".into(), value: "southeastasia".into() },
                    ],
                    help_text: Some("Azure region for the resource group".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "azurerm_virtual_network".into(),
            name: "Virtual Network".into(),
            resource_type: "azurerm_virtual_network".into(),
            provider_id: "azurerm".into(),
            category: "Network".into(),
            description: "An Azure virtual network (VNet)".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the virtual network".into()),
                },
                ProviderFieldSchema {
                    name: "address_space".into(),
                    label: "Address Space".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("10.0.0.0/16".into()),
                    options: vec![],
                    help_text: Some("CIDR address space for the VNet".into()),
                },
                ProviderFieldSchema {
                    name: "location".into(),
                    label: "Location".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure region (use azurerm_resource_group.*.location)".into()),
                },
                ProviderFieldSchema {
                    name: "resource_group_name".into(),
                    label: "Resource Group Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the resource group".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "azurerm_linux_virtual_machine".into(),
            name: "Linux VM".into(),
            resource_type: "azurerm_linux_virtual_machine".into(),
            provider_id: "azurerm".into(),
            category: "Compute".into(),
            description: "An Azure Linux virtual machine".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the virtual machine".into()),
                },
                ProviderFieldSchema {
                    name: "resource_group_name".into(),
                    label: "Resource Group Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the resource group".into()),
                },
                ProviderFieldSchema {
                    name: "location".into(),
                    label: "Location".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure region for the VM".into()),
                },
                ProviderFieldSchema {
                    name: "size".into(),
                    label: "VM Size".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("Standard_B1s".into()),
                    options: vec![
                        FieldOption { label: "Standard_B1s".into(), value: "Standard_B1s".into() },
                        FieldOption { label: "Standard_B2s".into(), value: "Standard_B2s".into() },
                        FieldOption { label: "Standard_D2s_v3".into(), value: "Standard_D2s_v3".into() },
                        FieldOption { label: "Standard_D4s_v3".into(), value: "Standard_D4s_v3".into() },
                    ],
                    help_text: Some("Azure VM size".into()),
                },
                ProviderFieldSchema {
                    name: "admin_username".into(),
                    label: "Admin Username".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("azureuser".into()),
                    options: vec![],
                    help_text: Some("Admin username for the VM".into()),
                },
                ProviderFieldSchema {
                    name: "admin_password".into(),
                    label: "Admin Password".into(),
                    field_type: ProviderFieldType::Sensitive,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Admin password (or use SSH key)".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "azurerm_storage_account".into(),
            name: "Storage Account".into(),
            resource_type: "azurerm_storage_account".into(),
            provider_id: "azurerm".into(),
            category: "Storage".into(),
            description: "An Azure storage account".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Globally unique storage account name (lowercase, no hyphens)".into()),
                },
                ProviderFieldSchema {
                    name: "resource_group_name".into(),
                    label: "Resource Group Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the resource group".into()),
                },
                ProviderFieldSchema {
                    name: "location".into(),
                    label: "Location".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Azure region".into()),
                },
                ProviderFieldSchema {
                    name: "account_tier".into(),
                    label: "Account Tier".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("Standard".into()),
                    options: vec![
                        FieldOption { label: "Standard".into(), value: "Standard".into() },
                        FieldOption { label: "Premium".into(), value: "Premium".into() },
                    ],
                    help_text: Some("Performance tier".into()),
                },
                ProviderFieldSchema {
                    name: "account_replication_type".into(),
                    label: "Replication".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("LRS".into()),
                    options: vec![
                        FieldOption { label: "LRS (Locally Redundant)".into(), value: "LRS".into() },
                        FieldOption { label: "GRS (Geo-Redundant)".into(), value: "GRS".into() },
                        FieldOption { label: "ZRS (Zone-Redundant)".into(), value: "ZRS".into() },
                    ],
                    help_text: Some("Data replication strategy".into()),
                },
            ],
        },

        // ── GCP ──────────────────────────────────────────────
        ResourceCatalogEntry {
            id: "google_compute_instance".into(),
            name: "Compute Instance".into(),
            resource_type: "google_compute_instance".into(),
            provider_id: "google".into(),
            category: "Compute".into(),
            description: "A Google Compute Engine VM instance".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the instance".into()),
                },
                ProviderFieldSchema {
                    name: "machine_type".into(),
                    label: "Machine Type".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("e2-micro".into()),
                    options: vec![
                        FieldOption { label: "e2-micro".into(), value: "e2-micro".into() },
                        FieldOption { label: "e2-small".into(), value: "e2-small".into() },
                        FieldOption { label: "e2-medium".into(), value: "e2-medium".into() },
                        FieldOption { label: "n1-standard-1".into(), value: "n1-standard-1".into() },
                        FieldOption { label: "n1-standard-2".into(), value: "n1-standard-2".into() },
                    ],
                    help_text: Some("GCE machine type".into()),
                },
                ProviderFieldSchema {
                    name: "zone".into(),
                    label: "Zone".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("us-central1-a".into()),
                    options: vec![],
                    help_text: Some("GCP zone for the instance".into()),
                },
                ProviderFieldSchema {
                    name: "boot_disk_image".into(),
                    label: "Boot Disk Image".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: Some("debian-cloud/debian-11".into()),
                    options: vec![],
                    help_text: Some("Source image for the boot disk".into()),
                },
                ProviderFieldSchema {
                    name: "network".into(),
                    label: "Network".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("default".into()),
                    options: vec![],
                    help_text: Some("Network to attach the instance to".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "google_storage_bucket".into(),
            name: "Cloud Storage Bucket".into(),
            resource_type: "google_storage_bucket".into(),
            provider_id: "google".into(),
            category: "Storage".into(),
            description: "A Google Cloud Storage bucket".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Bucket Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Globally unique bucket name".into()),
                },
                ProviderFieldSchema {
                    name: "location".into(),
                    label: "Location".into(),
                    field_type: ProviderFieldType::Select,
                    required: true,
                    default_value: Some("US".into()),
                    options: vec![
                        FieldOption { label: "US (multi-region)".into(), value: "US".into() },
                        FieldOption { label: "EU (multi-region)".into(), value: "EU".into() },
                        FieldOption { label: "ASIA (multi-region)".into(), value: "ASIA".into() },
                        FieldOption { label: "us-central1".into(), value: "us-central1".into() },
                        FieldOption { label: "europe-west1".into(), value: "europe-west1".into() },
                    ],
                    help_text: Some("Bucket location".into()),
                },
                ProviderFieldSchema {
                    name: "force_destroy".into(),
                    label: "Force Destroy".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("false".into()),
                    options: vec![],
                    help_text: Some("Allow deletion even if bucket contains objects".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "google_compute_network".into(),
            name: "VPC Network".into(),
            resource_type: "google_compute_network".into(),
            provider_id: "google".into(),
            category: "Network".into(),
            description: "A Google Compute Engine VPC network".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the VPC network".into()),
                },
                ProviderFieldSchema {
                    name: "auto_create_subnetworks".into(),
                    label: "Auto Create Subnetworks".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Automatically create subnets in each region".into()),
                },
            ],
        },

        // ── Docker ───────────────────────────────────────────
        ResourceCatalogEntry {
            id: "docker_container".into(),
            name: "Docker Container".into(),
            resource_type: "docker_container".into(),
            provider_id: "docker".into(),
            category: "Container".into(),
            description: "A Docker container".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Container Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the container".into()),
                },
                ProviderFieldSchema {
                    name: "image".into(),
                    label: "Image".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Docker image name (use docker_image resource ID)".into()),
                },
                ProviderFieldSchema {
                    name: "ports_internal".into(),
                    label: "Internal Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Container port to expose".into()),
                },
                ProviderFieldSchema {
                    name: "ports_external".into(),
                    label: "External Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Host port to bind to".into()),
                },
                ProviderFieldSchema {
                    name: "env".into(),
                    label: "Environment Variables".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Comma-separated KEY=VALUE pairs".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "docker_image".into(),
            name: "Docker Image".into(),
            resource_type: "docker_image".into(),
            provider_id: "docker".into(),
            category: "Container".into(),
            description: "A Docker image to pull".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Image Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Image name with optional tag (e.g. nginx:latest)".into()),
                },
                ProviderFieldSchema {
                    name: "keep_locally".into(),
                    label: "Keep Locally".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("false".into()),
                    options: vec![],
                    help_text: Some("Keep the image when destroying the resource".into()),
                },
            ],
        },

        // ── Kubernetes ───────────────────────────────────────
        ResourceCatalogEntry {
            id: "kubernetes_namespace".into(),
            name: "Namespace".into(),
            resource_type: "kubernetes_namespace".into(),
            provider_id: "kubernetes".into(),
            category: "Container".into(),
            description: "A Kubernetes namespace".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the namespace".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "kubernetes_deployment".into(),
            name: "Deployment".into(),
            resource_type: "kubernetes_deployment".into(),
            provider_id: "kubernetes".into(),
            category: "Container".into(),
            description: "A Kubernetes deployment".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the deployment".into()),
                },
                ProviderFieldSchema {
                    name: "namespace".into(),
                    label: "Namespace".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("default".into()),
                    options: vec![],
                    help_text: Some("Kubernetes namespace".into()),
                },
                ProviderFieldSchema {
                    name: "replicas".into(),
                    label: "Replicas".into(),
                    field_type: ProviderFieldType::Number,
                    required: false,
                    default_value: Some("1".into()),
                    options: vec![],
                    help_text: Some("Number of pod replicas".into()),
                },
                ProviderFieldSchema {
                    name: "container_name".into(),
                    label: "Container Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the container in the pod".into()),
                },
                ProviderFieldSchema {
                    name: "container_image".into(),
                    label: "Container Image".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Container image (e.g. nginx:1.25)".into()),
                },
                ProviderFieldSchema {
                    name: "container_port".into(),
                    label: "Container Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Port the container listens on".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "kubernetes_service".into(),
            name: "Service".into(),
            resource_type: "kubernetes_service".into(),
            provider_id: "kubernetes".into(),
            category: "Container".into(),
            description: "A Kubernetes service for load balancing".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "name".into(),
                    label: "Name".into(),
                    field_type: ProviderFieldType::String,
                    required: true,
                    default_value: None,
                    options: vec![],
                    help_text: Some("Name of the service".into()),
                },
                ProviderFieldSchema {
                    name: "namespace".into(),
                    label: "Namespace".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: Some("default".into()),
                    options: vec![],
                    help_text: Some("Kubernetes namespace".into()),
                },
                ProviderFieldSchema {
                    name: "type".into(),
                    label: "Service Type".into(),
                    field_type: ProviderFieldType::Select,
                    required: false,
                    default_value: Some("ClusterIP".into()),
                    options: vec![
                        FieldOption { label: "ClusterIP".into(), value: "ClusterIP".into() },
                        FieldOption { label: "NodePort".into(), value: "NodePort".into() },
                        FieldOption { label: "LoadBalancer".into(), value: "LoadBalancer".into() },
                    ],
                    help_text: Some("Type of Kubernetes service".into()),
                },
                ProviderFieldSchema {
                    name: "port".into(),
                    label: "Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: true,
                    default_value: Some("80".into()),
                    options: vec![],
                    help_text: Some("Service port".into()),
                },
                ProviderFieldSchema {
                    name: "target_port".into(),
                    label: "Target Port".into(),
                    field_type: ProviderFieldType::Number,
                    required: true,
                    default_value: Some("80".into()),
                    options: vec![],
                    help_text: Some("Port on the pods to forward to".into()),
                },
                ProviderFieldSchema {
                    name: "selector_app".into(),
                    label: "Selector (app)".into(),
                    field_type: ProviderFieldType::String,
                    required: false,
                    default_value: None,
                    options: vec![],
                    help_text: Some("app label to match pods".into()),
                },
            ],
        },

        // ── Random ───────────────────────────────────────────
        ResourceCatalogEntry {
            id: "random_string".into(),
            name: "Random String".into(),
            resource_type: "random_string".into(),
            provider_id: "random".into(),
            category: "Utility".into(),
            description: "Generate a random string".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "length".into(),
                    label: "Length".into(),
                    field_type: ProviderFieldType::Number,
                    required: true,
                    default_value: Some("16".into()),
                    options: vec![],
                    help_text: Some("Length of the generated string".into()),
                },
                ProviderFieldSchema {
                    name: "special".into(),
                    label: "Include Special Chars".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Include special characters".into()),
                },
                ProviderFieldSchema {
                    name: "upper".into(),
                    label: "Include Uppercase".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Include uppercase letters".into()),
                },
            ],
        },
        ResourceCatalogEntry {
            id: "random_password".into(),
            name: "Random Password".into(),
            resource_type: "random_password".into(),
            provider_id: "random".into(),
            category: "Utility".into(),
            description: "Generate a random password (marked sensitive)".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "length".into(),
                    label: "Length".into(),
                    field_type: ProviderFieldType::Number,
                    required: true,
                    default_value: Some("24".into()),
                    options: vec![],
                    help_text: Some("Length of the generated password".into()),
                },
                ProviderFieldSchema {
                    name: "special".into(),
                    label: "Include Special Chars".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("true".into()),
                    options: vec![],
                    help_text: Some("Include special characters".into()),
                },
            ],
        },

        // ── Null ─────────────────────────────────────────────
        ResourceCatalogEntry {
            id: "null_resource".into(),
            name: "Null Resource".into(),
            resource_type: "null_resource".into(),
            provider_id: "null".into(),
            category: "Utility".into(),
            description: "A placeholder resource for triggers and provisioners".into(),
            fields: vec![
                ProviderFieldSchema {
                    name: "triggers_always".into(),
                    label: "Always Run".into(),
                    field_type: ProviderFieldType::Bool,
                    required: false,
                    default_value: Some("false".into()),
                    options: vec![],
                    help_text: Some("Use a timestamp trigger to always re-run".into()),
                },
            ],
        },
    ]
}
